# To configure a conda environment, run
#    conda env create -f environment.yml
#
name: 20210616-rainier-b
channels:
  - conda-forge
  - defaults
dependencies:
  #- gdal==3.0.4
  #- fiona==1.8.13
  #- geopandas==0.8.1
  #- hdf4==4.2.13
  #- hdf5==1.10.6
  - matplotlib
  - numpy
  - pandas==1.0.5
  #- pip
  - scipy
  - tqdm

